services:
  - type: web
    name: tx-md5-predict
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn app_tx_md5:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120"
